packages/titanium-docgen/generators/html_generator.js
This is a porting of https://github.com/appcelerator/titanium_mobile/pull/11052/commits/c760b75156f2827409be12ebf17b3a100d72aecd
=> fix(docgen): correctly handle array syntax in callbacks

packages/titanium-docgen/validate.js
So the validation already supports a `--standalone` flag, but that basically just ignores when we can't resolve a type. So it can't really catch if there's a typo or reference to non-existing type.
This adds a more selective variant where you supply "whitelisted" type name and any unresolved references to these types are ignored. Basically it forces you to specifically say that these are known good types.
I tested this manually out on ti.map module:
```
node validate.js -w Point -w Titanium.Blob -w Titanium.UI.View -w Titanium.Proxy -w Titanium.Module -w Titanium.UI.iOS.PreviewContext /Users/cwilliams/repos/ti.map/apidoc
```
With standalone mode it would log warnings about all those types. Without, it would error on all those types. With whitelist it does neither.
The relevant use case is …
=> feat(validate): add ability to whitelist types

packages/vuepress/vuepress-plugin-versioning/lib/util.js
Fix sidebar snapshot to properly include the non-locale sidebar config which is found under `themeConfig` instead of the root of the config object.
=> fix(versioning): include non-locale sidebar config in snapshot

packages/titanium-docgen/lib/common.js
If I reference Error or RegEx types in our apidocs, we get an error. These are core pre-defined types in JS, and should be allowed. 
(for reference, the legacy doc publishing process uses Sencha/jsduck and also supports these types: https://github.com/senchalabs/jsduck/wiki/Type-Definitions - note that we will eventually have issues with es6+ types there).
=> fix(docgen): allow Error and RegExp as predefined types

packages/titanium-docgen/validate.js
Relates to appcelerator/titanium_mobile#11352
This is a fairly large refactor of the doc validation code. The aim here was to:
- clean up the code
- Move away from gathering strings in a tree-like object structure to gather problems with a message/severity in a flat Map by the full "key"
- Which allowed me to add warning-level "linting" so we can warn without "failing" the validation
Then I added warnings for some new things:
- Using bare Object/Dictionary types. In most cases these are a cop-out from declaring a very simple object type with a handful of properties. This does cause "false positives" which I haven't figured out how to avoid/skip (like eslint ignore markers, maybe we can add yml comments on the line to know to skip?)
- constants named LIKE_THIS that have a permission other …
=> feat(docgen): improve validation to include warnings

packages/titanium-docgen/lib/common.js
If you call the generator with `../titanium_mobile/apidoc/` as the input path it will build incorrect `__file` properties for APIs objects (e.g. `..apidoc//Titanium..`).
=> fix(docgen): build correct path

packages/titanium-docgen/generators/typescript_generator.js
```typescript
const button = Ti.UI.createButton({
width: 100,
backgroundColor: '#ddd',
text: '+',   // TS2345: [..] 'text' does not exist in type [..]
left: 10
});
```
```typescript
const button = Ti.UI.createButton();
button.addEventListener('click', function(e) {
this.backgroundColor = 'red';
this.text = 123;  // TS2339: Property 'text' does not exist on type 'Button'.
});
```
```typescript
const button = Ti.UI.createButton();
// know event type
button.addEventListener('click', function(e) {
e.source.backgroundColor = 'red';
console.log(`x: ${e.x}`);
console.log(`x: ${e.z}`);  // TS2339: Property 'z' does not exist on type 'Button_click_Event'.
});
// unknown event type
button.addEventListener('myEvent', function(e) {
console.log(e.lol);  // ok, because 'myEvent' is unknown event type …
```
=> feat(docgen): improve typescript generator

packages/titanium-docgen/index.js
- Get `version` from `package.json`
- For >= 8.0.0 mark accessors `deprecated` since `8.0.0`
- For >= ~9.0.0~ 10.0.0 mark accessors `removed` in ~`9.0.0`~ `10.0.0`
- Keep `since` and `notes` for already deprecated APIs
- Use in accessors deprecation descriptor from API for already removed APIs
=> feat(docgen): improve accessors generation. remove in 10.0.0

packages/titanium-docgen/generators/jsca_generator.js, packages/titanium-docgen/generators/jsduck_generator.js, packages/titanium-docgen/lib/common.js, packages/titanium-docgen/validate.js
Support API docs referencing types: Promise, ArrayBuffer, Typed Arrays, Map, Set
Our docgen scripts and validation didn't know about newer built-in JS types. This was because the scripts were originally written before they were introduced **and** because our jsduck tooling for docs.appcelerator.com couldn't handle them.
I've added support for them in our jsduck fork on this branch: https://github.com/appcelerator/jsduck/commits/sgtcoolguy-es6
And I've created a local branch of appcelerator/doctools repo that consumes that to produce the doc site. It seemed to work fine once I generated the titanium.js file via this PR's docgen jsduck output.
=> feat(docgen): support es6+ JS builtins

packages/docs/docs/.vuepress/config.js, packages/docs/docs/.vuepress/fa-icons.js, packages/docs/docs/guide/fontawesome.md, packages/docs/docs/plugins/README.md, packages/docs/docs/plugins/fontawesome-plugin.md, packages/docs/package.json, packages/vuepress/vuepress-plugin-fontawesome/README.md, packages/vuepress/vuepress-plugin-fontawesome/index.js, packages/vuepress/vuepress-plugin-fontawesome/lib/enhance.js, packages/vuepress/vuepress-plugin-fontawesome/lib/markdown.js, packages/vuepress/vuepress-plugin-fontawesome/package.json, yarn.lock
There already is an existing [FontAwesome plugin](https://www.npmjs.com/package/vuepress-plugin-font-awesome) but i found that it has a rather inconvenient usage. It generates one extra component for each icon which doesn't really match with how the official https://github.com/FortAwesome/vue-fontawesome Vue component works nowadays. So i decided to write our own updated version, which is based on the official https://github.com/markdown-it/markdown-it-emoji plugin.
- Markdown shorthand syntax similar to the emoji syntax: `:fas-coffee:`
- Supports all FontAwesome icons
- Uses the official vue-fontawesome components under the hood (enables tree-shaking to bundle used icons only)
=> feat: font awesome plugin

packages/titanium-docgen/generators/json-raw_generator.js, packages/vuepress/vuepress-theme-titanium/components/PageEdit.vue
These changes are to:
- export an editUrl property in the api.json generated from titanium-docgen for json-raw output type. This url should point to the exact URL used to edit the underlying file. (this is generated by deconstructing the yml filepath that we used to generate the type to try and pull out the git repo's origin remote url and turn it into a GitHub edit url)
- Allow the titanium theme to use a page's frontmatter `editUrl` value as the edit this page link if it's not "nil" (`null`/`undefined`)
We'll also need to tweak the appcelerator/titanium-docs repo's migrate script to stick the editUrl into the generated page frontmatter.
=> feat: allow editUrl

packages/vuepress/vuepress-plugin-versioning/index.js, packages/vuepress/vuepress-theme-titanium/components/PageEdit.vue
Fixes #48
Note that I did not test this with the versioning plugin (since we don't yet use it!) It *may* break versioned urls. I suspect that versioned urls need more tweaking anyways, because I'm not sure how to trace back a version to the original source markdown file on GitHub unless you can somehow supply a mapping from version to branch names or something.
=> fix(theme): use page relativePath to generate edit link

packages/titanium-docgen/lib/common.js, packages/vuepress/vuepress-plugin-apidocs/components/PropertyList.vue
Fixes `assertObjectKey` which would ignore keys which exists but have a falsy value. Also improves the display of default values for properties, which also would not show up if their value was falsy.
=> fix: properly handle falsy default values

package.json, packages/docs/package.json, packages/titanium-docgen/generators/html_generator.js, packages/titanium-docgen/generators/jsca_generator.js, packages/titanium-docgen/generators/jsduck_generator.js, packages/titanium-docgen/generators/json-raw_generator.js, packages/titanium-docgen/generators/json_generator.js, packages/titanium-docgen/generators/modulehtml_generator.js, packages/titanium-docgen/generators/parity_generator.js, packages/titanium-docgen/generators/solr_generator.js, packages/titanium-docgen/generators/typescript_generator.js, packages/titanium-docgen/index.js, packages/titanium-docgen/lib/common.js, packages/titanium-docgen/validate.js, packages/vuepress/vuepress-plugin-apidocs/package.json, packages/vuepress/vuepress-plugin-versioning/index.js, packages/vuepress/vuepress-plugin-versioning/package.json, packages/vuepress/vuepress-theme-titanium/package.json, yarn.lock
This updates all dependencies including the eslint update from #92 and also fixes all eslint errors that occurred because of bumping eslint two major versions.
Updated dependencies:
- Updated eslint to 7.12.1
- Updated all VuePress related packages to 1.7.1
Closes #92
=> Update dependencies and apply eslint fixes

packages/vuepress/vuepress-plugin-apidocs/styles/main.styl, packages/vuepress/vuepress-theme-titanium/components/SidebarGroup.vue, packages/vuepress/vuepress-theme-titanium/styles/table.styl
This changes a couple of styles:
- Use a lighter shade of grey for table borders and the type signature left border
- Fix level 2 sub group heading which were slightly shifted
- Lower the margin between type metadata to save vertical space
=> fix: fix color shades, sidebar sub groups and type meta padding

packages/vuepress/vuepress-theme-titanium/styles/code.styl, packages/vuepress/vuepress-theme-titanium/styles/palette.styl
This tries to get the colors used in code snippets to match better with the colors from our theme. For that i took the Palenight High Contrast theme from VSCode as a base and changed some colors with the ones from our style guide.
I also enabled webkit font smoothing which makes the monospaced font in code block look a lot better in WebKit based browsers.
=> feat(theme): custom color theme for prism.js

packages/titanium-docgen/index.js
This reduced the JSCA file size from ~34MB to ~8MB by doing the following:
* Don't pretty print the file, just have a nice lovely minified blob of JSON
* No longer generate the accessors for every property, as the SDK doesn't anymore
* Technically a breaking change
The file produced by this has been verified to work with both the editors and Studio
=> Reduce jsca file size

packages/vuepress/vuepress-theme-titanium/plugins/smoothScroll/enhanceApp.js
Fixes https://github.com/tidev/titanium-docs/issues/
Sometimes `onLoad` is trigger and sometimes not. Catching that with the setTimeout. Not the best solution but it makes the anchor links and search work again!
**Test:**
* go to https://titaniumsdk.com/api/titanium/ui/window.html#extendedges
* click on `Titanium.UI.EXTEND_EDGE_BOTTOM`
* current page won't scroll to it
* navigate back and check if it scrolls to the correct anchor again
**Test2**
* search for `addMarker` and click the link
* check if it scrolls to the anchor
=> fix: anchor scroll

packages/vuepress/vuepress-plugin-apidocs/components/EventList.vue, packages/vuepress/vuepress-plugin-apidocs/components/MethodList.vue, packages/vuepress/vuepress-plugin-apidocs/components/PropertyList.vue, packages/vuepress/vuepress-plugin-apidocs/lib/metadata/processor.js
fixes https://github.com/tidev/titanium-docs/issues/45
I've added `methods_...` to the links in the side-menu so they are unique. If you go to https://titaniumsdk.com/api/modules/map/view.html and click on `userLocation` (event) it will scroll to `userLocation` (property). 
To keep all existing links I've moved the unprefixed ID to the div above it. So you can still use `/api/titanium/ui.html#createactivityindicator` and `/api/titanium/ui.html#methods_createactivityindicator` (unique)
=> feat(docs): fix menu links

packages/vuepress/vuepress-plugin-apidocs/lib/metadata/processor.js
fixes https://github.com/tidev/titanium-docs/issues/75 !
Currently the extended methods aren't visible in the docs (left side), with this PR it will add all of them:
https://titaniumsdk.com/api/titanium/ui/scrollview.html
I just uncomment the function that excluded them. In the future it would be good to add a special class to them and show that they are inherited.
=> feat(docs): show inherit elements

packages/vuepress/vuepress-plugin-apidocs/components/PropertyList.vue
Did a copy&paste error in the properties h3 in the last commit:
the old H3 line shouldn't be there! It's complaining at the moment that a closing h3 is missing
=> fix: h3 copy&paste error

packages/vuepress/vuepress-theme-titanium/index.js, packages/vuepress/vuepress-theme-titanium/styles/theme.styl
display more search results (30 instead of 10) but keeping the max. height of the search results the same height (with scrolling)
=> feat: more search results

packages/vuepress/vuepress-plugin-apidocs/components/ConstantList.vue, packages/vuepress/vuepress-plugin-apidocs/lib/metadata/processor.js
Resolves https://github.com/tidev/titanium-docs/issues/44
Current constants menu is empty but items are in the page:
https://titaniumsdk.com/api/titanium/ui/android.html#constants
With this PR the menu will be populated again:
=> feat: show constants again

packages/titanium-docgen/generators/typescript_generator.js
Had to change some namespaces to interfaces so https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64580 tests will succeed. 
Errors before e.g.
```
'Titanium.Calendar.RecurrenceRule' refers to a value, but is being used as a type here. Did you mean 'typeof Titanium.Calendar.RecurrenceRule'?
```
=> fix: docgen interfaces

packages/vuepress/vuepress-theme-titanium/plugins/smoothScroll/enhanceApp.js
Currently pages without a hashtag show a warning:
`Empty string passed to getElementById().`
This fix will check for empty hashtags
=> fix 'Empty string passed to getElementById()'
